services:
  trademark-proxy:
    build: .
    container_name: trademark-proxy
    ports:
      - 8181:8181
    volumes:
      - "/usr/local/servers/proxy/logs:/app/proxy/logs"
    environment:
      PORT: 8181

  portainer:
    image: "portainer/portainer-ce:2.20.3"
    container_name: portainer
    command: "-H unix:///var/run/docker.sock"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    ports:
      - "9000:9000"
    restart: always
volumes:
  portainer_data:
