services:
  trademark-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: "trademark-proxy:${VERSION}"
    container_name: trademark-proxy
    ports:
      - 8181:8181
      - 8443:8443
    volumes:
      - "/usr/local/servers/proxy/logs:/app/proxy/logs"
    environment:
      PORT: 8181
      SSL_PORT: 8443
      URL_HREF: "/profile/help/trademark-search"
      LOG_LEVEL: "info"

  portainer:
    image: "portainer/portainer-ce:2.20.3"
    container_name: portainer
    command: "-H unix:///var/run/docker.sock"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    ports:
      - "9000:9000"
    restart: always
volumes:
  portainer_data:
